2025-03-10 23:55:25,440 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-10 23:55:26,093 - INFO - Driver headless inicializado correctamente
2025-03-10 23:55:26,093 - INFO - Iniciando proceso de login en Google
2025-03-10 23:55:27,137 - INFO - Esperando campo de email...
2025-03-10 23:55:27,521 - INFO - Captura guardada: screenshots/1_email_ingresado_20250310_235527.png
2025-03-10 23:55:27,691 - INFO - Email ingresado, pasando a contraseña
2025-03-10 23:55:27,691 - INFO - Esperando campo de contraseña...
2025-03-10 23:55:31,480 - INFO - Captura guardada: screenshots/2_password_ingresado_20250310_235531.png
2025-03-10 23:55:45,202 - INFO - Login completado exitosamente
2025-03-10 23:55:45,294 - INFO - Captura guardada: screenshots/3_login_completado_20250310_235545.png
2025-03-10 23:55:45,308 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-10 23:55:57,963 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-10 23:55:58,113 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250310_235557.png
2025-03-10 23:55:58,119 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-10 23:58:12,416 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,416 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190920>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,416 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190ad0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,417 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191730>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,417 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,418 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,418 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b1920c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,419 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192300>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,419 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192540>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,419 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b1929f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,420 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192b70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,421 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192d20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,422 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=38819): Max retries exceeded with url: /session/5e4a17519d06dc7ade3667083790b517/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-10 23:58:12,423 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192030>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/source
2025-03-10 23:58:12,424 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192720>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/source
2025-03-10 23:58:12,424 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/source
2025-03-10 23:58:12,425 - ERROR - Error al unirse a la reunión: HTTPConnectionPool(host='localhost', port=38819): Max retries exceeded with url: /session/5e4a17519d06dc7ade3667083790b517/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192330>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-10 23:58:12,427 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192120>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,428 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190dd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,429 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191a00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,429 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=38819): Max retries exceeded with url: /session/5e4a17519d06dc7ade3667083790b517/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-10 23:58:12,430 - INFO - Permaneciendo en la reunión por 60 minutos
2025-03-10 23:58:12,431 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191940>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,431 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191730>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,432 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190b00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,432 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=38819): Max retries exceeded with url: /session/5e4a17519d06dc7ade3667083790b517/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-10 23:58:12,432 - INFO - Todavía en la reunión - 0 minutos transcurridos
2025-03-10 23:58:16,385 - INFO - Cerrando el navegador
2025-03-11 00:14:07,387 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 00:14:07,723 - INFO - Driver headless inicializado correctamente
2025-03-11 00:14:07,723 - INFO - Iniciando proceso de login en Google
2025-03-11 00:14:12,609 - INFO - Esperando campo de email...
2025-03-11 00:14:12,958 - INFO - Captura guardada: screenshots/1_email_ingresado_20250311_001412.png
2025-03-11 00:14:13,126 - INFO - Email ingresado, pasando a contraseña
2025-03-11 00:14:13,126 - INFO - Esperando campo de contraseña...
2025-03-11 00:14:16,888 - INFO - Captura guardada: screenshots/2_password_ingresado_20250311_001416.png
2025-03-11 00:14:27,022 - INFO - Login completado exitosamente
2025-03-11 00:14:27,102 - INFO - Captura guardada: screenshots/3_login_completado_20250311_001427.png
2025-03-11 00:14:27,118 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:14:39,110 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:14:39,200 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250311_001439.png
2025-03-11 00:14:39,320 - INFO - Captura guardada: screenshots/esperandocontroles_20250311_001439.png
2025-03-11 00:14:39,320 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-11 00:14:44,425 - INFO - Captura guardada: screenshots/controlesnada_20250311_001444.png
2025-03-11 00:15:18,357 - INFO - Cámara desactivada con selector: [data-is-muted='false'][aria-label*='camera']
2025-03-11 00:15:52,342 - INFO - Micrófono desactivado con selector: [data-is-muted='false'][aria-label*='microphone']
2025-03-11 00:15:52,482 - INFO - Captura guardada: screenshots/5_antes_de_unirse_20250311_001552.png
2025-03-11 00:15:52,564 - INFO - Intentando con selector: [jsname='CQylAd']
2025-03-11 00:16:26,388 - INFO - Intentando con selector: button[jsname='Qx7uuf']
2025-03-11 00:16:48,790 - INFO - Cerrando el navegador
2025-03-11 00:26:23,467 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 00:26:24,035 - INFO - Driver headless inicializado correctamente
2025-03-11 00:26:24,035 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:26:36,923 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:26:37,024 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_002636.png
2025-03-11 00:26:37,024 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 00:26:37,222 - INFO - Nombre ingresado con selector: input[type='text']
2025-03-11 00:26:37,337 - INFO - Captura guardada: screenshots/2_nombre_ingresado_20250311_002637.png
2025-03-11 00:26:37,337 - INFO - Configurando cámara y micrófono...
2025-03-11 00:26:37,434 - INFO - Captura guardada: screenshots/3_antes_de_configurar_dispositivos_20250311_002637.png
2025-03-11 00:26:37,583 - INFO - Captura guardada: screenshots/4_antes_de_pedir_unirse_20250311_002637.png
2025-03-11 00:26:37,737 - INFO - Botón 'Pedir unirse' encontrado y clicado con selector: button[aria-label*='join']
2025-03-11 00:26:37,737 - INFO - Esperando a que se acepte la solicitud de unirse...
2025-03-11 00:26:51,401 - INFO - Captura guardada: screenshots/5_esperando_aceptacion_20250311_002651.png
2025-03-11 00:26:51,494 - INFO - Captura guardada: screenshots/verificacion_0_20250311_002651.png
2025-03-11 00:27:01,614 - INFO - Captura guardada: screenshots/verificacion_1_20250311_002701.png
2025-03-11 00:27:11,747 - INFO - Captura guardada: screenshots/verificacion_2_20250311_002711.png
2025-03-11 00:27:25,468 - INFO - Captura guardada: screenshots/verificacion_3_20250311_002725.png
2025-03-11 00:27:32,292 - INFO - Cerrando el navegador
