2025-03-10 23:55:25,440 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-10 23:55:26,093 - INFO - Driver headless inicializado correctamente
2025-03-10 23:55:26,093 - INFO - Iniciando proceso de login en Google
2025-03-10 23:55:27,137 - INFO - Esperando campo de email...
2025-03-10 23:55:27,521 - INFO - Captura guardada: screenshots/1_email_ingresado_20250310_235527.png
2025-03-10 23:55:27,691 - INFO - Email ingresado, pasando a contraseña
2025-03-10 23:55:27,691 - INFO - Esperando campo de contraseña...
2025-03-10 23:55:31,480 - INFO - Captura guardada: screenshots/2_password_ingresado_20250310_235531.png
2025-03-10 23:55:45,202 - INFO - Login completado exitosamente
2025-03-10 23:55:45,294 - INFO - Captura guardada: screenshots/3_login_completado_20250310_235545.png
2025-03-10 23:55:45,308 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-10 23:55:57,963 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-10 23:55:58,113 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250310_235557.png
2025-03-10 23:55:58,119 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-10 23:58:12,416 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,416 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190920>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,416 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190ad0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,417 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191730>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,417 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,418 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,418 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b1920c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,419 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192300>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,419 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192540>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/element
2025-03-10 23:58:12,419 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b1929f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,420 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192b70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,421 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192d20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,422 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=38819): Max retries exceeded with url: /session/5e4a17519d06dc7ade3667083790b517/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-10 23:58:12,423 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192030>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/source
2025-03-10 23:58:12,424 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192720>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/source
2025-03-10 23:58:12,424 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/source
2025-03-10 23:58:12,425 - ERROR - Error al unirse a la reunión: HTTPConnectionPool(host='localhost', port=38819): Max retries exceeded with url: /session/5e4a17519d06dc7ade3667083790b517/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192330>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-10 23:58:12,427 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b192120>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,428 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190dd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,429 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191a00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,429 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=38819): Max retries exceeded with url: /session/5e4a17519d06dc7ade3667083790b517/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-10 23:58:12,430 - INFO - Permaneciendo en la reunión por 60 minutos
2025-03-10 23:58:12,431 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191940>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,431 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b191730>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,432 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190b00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e4a17519d06dc7ade3667083790b517/screenshot
2025-03-10 23:58:12,432 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=38819): Max retries exceeded with url: /session/5e4a17519d06dc7ade3667083790b517/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f304b190b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-10 23:58:12,432 - INFO - Todavía en la reunión - 0 minutos transcurridos
2025-03-10 23:58:16,385 - INFO - Cerrando el navegador
2025-03-11 00:14:07,387 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 00:14:07,723 - INFO - Driver headless inicializado correctamente
2025-03-11 00:14:07,723 - INFO - Iniciando proceso de login en Google
2025-03-11 00:14:12,609 - INFO - Esperando campo de email...
2025-03-11 00:14:12,958 - INFO - Captura guardada: screenshots/1_email_ingresado_20250311_001412.png
2025-03-11 00:14:13,126 - INFO - Email ingresado, pasando a contraseña
2025-03-11 00:14:13,126 - INFO - Esperando campo de contraseña...
2025-03-11 00:14:16,888 - INFO - Captura guardada: screenshots/2_password_ingresado_20250311_001416.png
2025-03-11 00:14:27,022 - INFO - Login completado exitosamente
2025-03-11 00:14:27,102 - INFO - Captura guardada: screenshots/3_login_completado_20250311_001427.png
2025-03-11 00:14:27,118 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:14:39,110 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:14:39,200 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250311_001439.png
2025-03-11 00:14:39,320 - INFO - Captura guardada: screenshots/esperandocontroles_20250311_001439.png
2025-03-11 00:14:39,320 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-11 00:14:44,425 - INFO - Captura guardada: screenshots/controlesnada_20250311_001444.png
2025-03-11 00:15:18,357 - INFO - Cámara desactivada con selector: [data-is-muted='false'][aria-label*='camera']
2025-03-11 00:15:52,342 - INFO - Micrófono desactivado con selector: [data-is-muted='false'][aria-label*='microphone']
2025-03-11 00:15:52,482 - INFO - Captura guardada: screenshots/5_antes_de_unirse_20250311_001552.png
2025-03-11 00:15:52,564 - INFO - Intentando con selector: [jsname='CQylAd']
2025-03-11 00:16:26,388 - INFO - Intentando con selector: button[jsname='Qx7uuf']
2025-03-11 00:16:48,790 - INFO - Cerrando el navegador
2025-03-11 00:26:23,467 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 00:26:24,035 - INFO - Driver headless inicializado correctamente
2025-03-11 00:26:24,035 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:26:36,923 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:26:37,024 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_002636.png
2025-03-11 00:26:37,024 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 00:26:37,222 - INFO - Nombre ingresado con selector: input[type='text']
2025-03-11 00:26:37,337 - INFO - Captura guardada: screenshots/2_nombre_ingresado_20250311_002637.png
2025-03-11 00:26:37,337 - INFO - Configurando cámara y micrófono...
2025-03-11 00:26:37,434 - INFO - Captura guardada: screenshots/3_antes_de_configurar_dispositivos_20250311_002637.png
2025-03-11 00:26:37,583 - INFO - Captura guardada: screenshots/4_antes_de_pedir_unirse_20250311_002637.png
2025-03-11 00:26:37,737 - INFO - Botón 'Pedir unirse' encontrado y clicado con selector: button[aria-label*='join']
2025-03-11 00:26:37,737 - INFO - Esperando a que se acepte la solicitud de unirse...
2025-03-11 00:26:51,401 - INFO - Captura guardada: screenshots/5_esperando_aceptacion_20250311_002651.png
2025-03-11 00:26:51,494 - INFO - Captura guardada: screenshots/verificacion_0_20250311_002651.png
2025-03-11 00:27:01,614 - INFO - Captura guardada: screenshots/verificacion_1_20250311_002701.png
2025-03-11 00:27:11,747 - INFO - Captura guardada: screenshots/verificacion_2_20250311_002711.png
2025-03-11 00:27:25,468 - INFO - Captura guardada: screenshots/verificacion_3_20250311_002725.png
2025-03-11 00:27:32,292 - INFO - Cerrando el navegador
2025-03-11 00:38:14,663 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 00:38:15,179 - INFO - Driver headless inicializado correctamente
2025-03-11 00:38:15,179 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:38:28,895 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:38:28,994 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_003828.png
2025-03-11 00:38:28,995 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 00:38:29,198 - INFO - Nombre ingresado con selector: input[type='text']
2025-03-11 00:38:29,308 - INFO - Captura guardada: screenshots/2_nombre_ingresado_20250311_003829.png
2025-03-11 00:38:29,308 - INFO - Configurando cámara y micrófono...
2025-03-11 00:38:29,408 - INFO - Captura guardada: screenshots/3_antes_de_configurar_dispositivos_20250311_003829.png
2025-03-11 00:38:29,541 - INFO - Captura guardada: screenshots/4_antes_de_pedir_unirse_20250311_003829.png
2025-03-11 00:38:29,694 - INFO - Botón 'Pedir unirse' encontrado y clicado con selector: button[aria-label*='join']
2025-03-11 00:38:29,694 - INFO - Esperando a que se acepte la solicitud de unirse...
2025-03-11 00:38:43,380 - INFO - Captura guardada: screenshots/5_esperando_aceptacion_20250311_003843.png
2025-03-11 00:38:43,474 - INFO - Captura guardada: screenshots/verificacion_0_20250311_003843.png
2025-03-11 00:38:53,593 - INFO - Captura guardada: screenshots/verificacion_1_20250311_003853.png
2025-03-11 00:39:03,729 - INFO - Captura guardada: screenshots/verificacion_2_20250311_003903.png
2025-03-11 00:39:17,461 - INFO - Captura guardada: screenshots/verificacion_3_20250311_003913.png
2025-03-11 00:39:27,576 - INFO - Captura guardada: screenshots/verificacion_4_20250311_003927.png
2025-03-11 00:39:35,593 - INFO - Cerrando el navegador
2025-03-11 00:43:50,953 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 00:43:51,306 - INFO - Driver headless inicializado correctamente
2025-03-11 00:43:51,306 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:44:07,914 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:44:08,024 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_004407.png
2025-03-11 00:44:08,024 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 00:45:18,815 - INFO - Cerrando el navegador
2025-03-11 00:46:08,231 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 00:46:08,563 - INFO - Driver headless inicializado correctamente
2025-03-11 00:46:08,563 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:46:22,236 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:46:22,385 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_004622.png
2025-03-11 00:46:22,385 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 00:48:31,498 - INFO - Cerrando el navegador
2025-03-11 00:52:26,539 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 00:52:26,976 - INFO - Driver headless inicializado correctamente
2025-03-11 00:52:26,976 - INFO - Iniciando proceso de login en Google
2025-03-11 00:52:28,458 - INFO - Esperando campo de email...
2025-03-11 00:52:28,991 - INFO - Captura guardada: screenshots/1_email_ingresado_20250311_005228.png
2025-03-11 00:52:29,240 - INFO - Email ingresado, pasando a contraseña
2025-03-11 00:52:29,240 - INFO - Esperando campo de contraseña...
2025-03-11 00:52:33,052 - INFO - Captura guardada: screenshots/2_password_ingresado_20250311_005232.png
2025-03-11 00:52:43,193 - INFO - Login completado exitosamente
2025-03-11 00:52:43,290 - INFO - Captura guardada: screenshots/3_login_completado_20250311_005243.png
2025-03-11 00:52:43,304 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:52:56,139 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:52:56,240 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250311_005256.png
2025-03-11 00:52:56,338 - INFO - Captura guardada: screenshots/esperandocontroles_20250311_005256.png
2025-03-11 00:52:56,338 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-11 00:53:05,032 - INFO - Captura guardada: screenshots/controlesnada_20250311_005304.png
2025-03-11 00:53:20,556 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b4cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,556 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b4800>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,557 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b4d70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,557 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b49b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,558 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b55b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,558 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b57f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,560 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b5d60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,560 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b5fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,561 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b61e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,562 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b6750>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,562 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b6990>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,563 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b6bd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,564 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b6420>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,565 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b61b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,567 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b5d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,568 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b5a30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,568 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b57c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,569 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b4b60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/element
2025-03-11 00:53:20,570 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b4860>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot
2025-03-11 00:53:20,570 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b4d10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot
2025-03-11 00:53:20,570 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b6cc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot
2025-03-11 00:53:20,571 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=52777): Max retries exceeded with url: /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b6f00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 00:53:20,571 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b7170>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/source
2025-03-11 00:53:20,572 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b7380>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/source
2025-03-11 00:53:20,573 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b7530>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/source
2025-03-11 00:53:20,573 - ERROR - Error al unirse a la reunión: HTTPConnectionPool(host='localhost', port=52777): Max retries exceeded with url: /session/5aa9a6098a88267f8ce34c522cbb2b4a/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b4830>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 00:53:20,573 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b6f00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot
2025-03-11 00:53:20,574 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b6de0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot
2025-03-11 00:53:20,574 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b4c20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot
2025-03-11 00:53:20,574 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=52777): Max retries exceeded with url: /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b58e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 00:53:20,574 - INFO - Permaneciendo en la reunión por 60 minutos
2025-03-11 00:53:20,575 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b5640>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot
2025-03-11 00:53:20,575 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b48c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot
2025-03-11 00:53:20,576 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b5610>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot
2025-03-11 00:53:20,576 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=52777): Max retries exceeded with url: /session/5aa9a6098a88267f8ce34c522cbb2b4a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59c87b5ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 00:53:20,576 - INFO - Todavía en la reunión - 0 minutos transcurridos
2025-03-11 00:53:24,267 - INFO - Cerrando el navegador
2025-03-11 00:53:40,754 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 00:53:41,329 - INFO - Driver headless inicializado correctamente
2025-03-11 00:53:41,330 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:54:03,969 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 00:54:04,086 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_005403.png
2025-03-11 00:54:04,086 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 00:54:38,177 - INFO - Cerrando el navegador
2025-03-11 01:06:00,999 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 01:06:01,529 - INFO - Driver headless inicializado correctamente
2025-03-11 01:06:01,529 - INFO - Iniciando proceso de login en Google
2025-03-11 01:06:02,554 - INFO - Esperando campo de email...
2025-03-11 01:06:02,928 - INFO - Captura guardada: screenshots/1_email_ingresado_20250311_010602.png
2025-03-11 01:06:03,094 - INFO - Email ingresado, pasando a contraseña
2025-03-11 01:06:03,094 - INFO - Esperando campo de contraseña...
2025-03-11 01:06:10,960 - INFO - Captura guardada: screenshots/2_password_ingresado_20250311_010610.png
2025-03-11 01:06:16,193 - INFO - Captura guardada: screenshots/post_password_page_20250311_010616.png
2025-03-11 01:06:16,207 - ERROR - Error en la ejecución principal: cannot access local variable 'start_time' where it is not associated with a value
2025-03-11 01:06:16,207 - INFO - Cerrando el navegador
2025-03-11 01:14:05,759 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 01:14:06,120 - INFO - Driver headless inicializado correctamente
2025-03-11 01:14:06,121 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/buv-dknh-dsx
2025-03-11 01:14:32,993 - INFO - URL actual: https://meet.google.com/buv-dknh-dsx
2025-03-11 01:14:33,097 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_011432.png
2025-03-11 01:14:33,097 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 01:14:33,282 - INFO - Nombre ingresado con selector: input[type='text']
2025-03-11 01:14:33,395 - INFO - Captura guardada: screenshots/2_nombre_ingresado_20250311_011433.png
2025-03-11 01:14:33,395 - INFO - Configurando cámara y micrófono...
2025-03-11 01:14:33,494 - INFO - Captura guardada: screenshots/3_antes_de_configurar_dispositivos_20250311_011433.png
2025-03-11 01:14:33,593 - INFO - Captura guardada: screenshots/4_antes_de_pedir_unirse_20250311_011433.png
2025-03-11 01:14:33,986 - INFO - Encontrado botón con texto: Ask to join
2025-03-11 01:14:34,138 - INFO - Esperando a que se acepte la solicitud de unirse...
2025-03-11 01:14:44,273 - INFO - Captura guardada: screenshots/5_esperando_aceptacion_20250311_011444.png
2025-03-11 01:14:44,403 - INFO - Captura guardada: screenshots/verificacion_0_20250311_011444.png
2025-03-11 01:14:48,179 - INFO - Cerrando el navegador
2025-03-11 01:18:43,250 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 01:18:43,851 - INFO - Driver headless inicializado correctamente
2025-03-11 01:18:43,852 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/buv-dknh-dsx
2025-03-11 01:19:06,159 - INFO - URL actual: https://meet.google.com/buv-dknh-dsx
2025-03-11 01:19:06,272 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_011906.png
2025-03-11 01:19:06,272 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 01:19:45,213 - INFO - Selector para nombre input[type='text'] falló: Message: 
Stacktrace:
#0 0x563fcf505a1a <unknown>
#1 0x563fcefbd390 <unknown>
#2 0x563fcf00ec85 <unknown>
#3 0x563fcf00eeb1 <unknown>
#4 0x563fcf05dd64 <unknown>
#5 0x563fcf034bfd <unknown>
#6 0x563fcf05b07b <unknown>
#7 0x563fcf0349a3 <unknown>
#8 0x563fcf00060e <unknown>
#9 0x563fcf001dd1 <unknown>
#10 0x563fcf4cbddb <unknown>
#11 0x563fcf4cfcbc <unknown>
#12 0x563fcf4b3392 <unknown>
#13 0x563fcf4d0834 <unknown>
#14 0x563fcf4971ef <unknown>
#15 0x563fcf4f4038 <unknown>
#16 0x563fcf4f4216 <unknown>
#17 0x563fcf504896 <unknown>
#18 0x7f447aa36aa4 <unknown>
#19 0x7f447aac3c3c <unknown>

2025-03-11 01:19:55,147 - INFO - Cerrando el navegador
2025-03-11 01:21:22,871 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 01:21:23,207 - INFO - Driver headless inicializado correctamente
2025-03-11 01:21:23,207 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/whq-cfhh-eji
2025-03-11 01:21:49,152 - INFO - URL actual: https://meet.google.com/whq-cfhh-eji
2025-03-11 01:21:49,258 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_012149.png
2025-03-11 01:21:49,258 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 01:22:28,130 - INFO - Selector para nombre input[type='text'] falló: Message: 
Stacktrace:
#0 0x55ef126e3a1a <unknown>
#1 0x55ef1219b390 <unknown>
#2 0x55ef121ecc85 <unknown>
#3 0x55ef121eceb1 <unknown>
#4 0x55ef1223bd64 <unknown>
#5 0x55ef12212bfd <unknown>
#6 0x55ef1223907b <unknown>
#7 0x55ef122129a3 <unknown>
#8 0x55ef121de60e <unknown>
#9 0x55ef121dfdd1 <unknown>
#10 0x55ef126a9ddb <unknown>
#11 0x55ef126adcbc <unknown>
#12 0x55ef12691392 <unknown>
#13 0x55ef126ae834 <unknown>
#14 0x55ef126751ef <unknown>
#15 0x55ef126d2038 <unknown>
#16 0x55ef126d2216 <unknown>
#17 0x55ef126e2896 <unknown>
#18 0x7f6918708aa4 <unknown>
#19 0x7f6918795c3c <unknown>

2025-03-11 01:23:07,014 - INFO - Selector para nombre input#mat-input-0 falló: Message: 
Stacktrace:
#0 0x55ef126e3a1a <unknown>
#1 0x55ef1219b390 <unknown>
#2 0x55ef121ecc85 <unknown>
#3 0x55ef121eceb1 <unknown>
#4 0x55ef1223bd64 <unknown>
#5 0x55ef12212bfd <unknown>
#6 0x55ef1223907b <unknown>
#7 0x55ef122129a3 <unknown>
#8 0x55ef121de60e <unknown>
#9 0x55ef121dfdd1 <unknown>
#10 0x55ef126a9ddb <unknown>
#11 0x55ef126adcbc <unknown>
#12 0x55ef12691392 <unknown>
#13 0x55ef126ae834 <unknown>
#14 0x55ef126751ef <unknown>
#15 0x55ef126d2038 <unknown>
#16 0x55ef126d2216 <unknown>
#17 0x55ef126e2896 <unknown>
#18 0x7f6918708aa4 <unknown>
#19 0x7f6918795c3c <unknown>

2025-03-11 01:23:45,885 - INFO - Selector para nombre input[aria-label*='name'] falló: Message: 
Stacktrace:
#0 0x55ef126e3a1a <unknown>
#1 0x55ef1219b390 <unknown>
#2 0x55ef121ecc85 <unknown>
#3 0x55ef121eceb1 <unknown>
#4 0x55ef1223bd64 <unknown>
#5 0x55ef12212bfd <unknown>
#6 0x55ef1223907b <unknown>
#7 0x55ef122129a3 <unknown>
#8 0x55ef121de60e <unknown>
#9 0x55ef121dfdd1 <unknown>
#10 0x55ef126a9ddb <unknown>
#11 0x55ef126adcbc <unknown>
#12 0x55ef12691392 <unknown>
#13 0x55ef126ae834 <unknown>
#14 0x55ef126751ef <unknown>
#15 0x55ef126d2038 <unknown>
#16 0x55ef126d2216 <unknown>
#17 0x55ef126e2896 <unknown>
#18 0x7f6918708aa4 <unknown>
#19 0x7f6918795c3c <unknown>

2025-03-11 01:23:55,723 - INFO - Cerrando el navegador
2025-03-11 01:24:08,127 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 01:24:08,671 - INFO - Driver headless inicializado correctamente
2025-03-11 01:24:08,671 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/whq-cfhh-eji
2025-03-11 01:24:28,217 - INFO - URL actual: https://meet.google.com/whq-cfhh-eji
2025-03-11 01:24:28,362 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_012428.png
2025-03-11 01:24:28,362 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 01:25:05,262 - INFO - Selector para nombre input[type='text'] falló: Message: 
Stacktrace:
#0 0x55f6c2faca1a <unknown>
#1 0x55f6c2a64390 <unknown>
#2 0x55f6c2ab5c85 <unknown>
#3 0x55f6c2ab5eb1 <unknown>
#4 0x55f6c2b04d64 <unknown>
#5 0x55f6c2adbbfd <unknown>
#6 0x55f6c2b0207b <unknown>
#7 0x55f6c2adb9a3 <unknown>
#8 0x55f6c2aa760e <unknown>
#9 0x55f6c2aa8dd1 <unknown>
#10 0x55f6c2f72ddb <unknown>
#11 0x55f6c2f76cbc <unknown>
#12 0x55f6c2f5a392 <unknown>
#13 0x55f6c2f77834 <unknown>
#14 0x55f6c2f3e1ef <unknown>
#15 0x55f6c2f9b038 <unknown>
#16 0x55f6c2f9b216 <unknown>
#17 0x55f6c2fab896 <unknown>
#18 0x7f7a21bbaaa4 <unknown>
#19 0x7f7a21c47c3c <unknown>

2025-03-11 01:25:07,851 - INFO - Cerrando el navegador
2025-03-11 01:25:19,507 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 01:25:19,829 - INFO - Driver headless inicializado correctamente
2025-03-11 01:25:19,829 - INFO - Iniciando proceso de login en Google
2025-03-11 01:25:20,870 - INFO - Esperando campo de email...
2025-03-11 01:25:21,203 - INFO - Captura guardada: screenshots/1_email_ingresado_20250311_012521.png
2025-03-11 01:25:21,361 - INFO - Email ingresado, pasando a contraseña
2025-03-11 01:25:21,361 - INFO - Esperando campo de contraseña...
2025-03-11 01:25:25,131 - INFO - Captura guardada: screenshots/2_password_ingresado_20250311_012525.png
2025-03-11 01:25:35,261 - INFO - Login completado exitosamente
2025-03-11 01:25:35,349 - INFO - Captura guardada: screenshots/3_login_completado_20250311_012535.png
2025-03-11 01:25:35,363 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-11 01:25:47,528 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 01:25:47,663 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250311_012547.png
2025-03-11 01:25:47,792 - INFO - Captura guardada: screenshots/esperandocontroles_20250311_012547.png
2025-03-11 01:25:47,792 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-11 01:25:56,505 - INFO - Captura guardada: screenshots/controlesnada_20250311_012556.png
2025-03-11 01:26:39,784 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5040>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,785 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e4d70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,786 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5100>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,788 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e4d10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,789 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5760>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,790 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e59a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,791 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,794 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e6150>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,798 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e6390>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,800 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e6900>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,801 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e6b40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,802 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e6d80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,803 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e65d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,804 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e6360>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,805 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5f40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/element
2025-03-11 01:26:39,806 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot
2025-03-11 01:26:39,807 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot
2025-03-11 01:26:39,807 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e58b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot
2025-03-11 01:26:39,808 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=37107): Max retries exceeded with url: /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e4d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 01:26:39,809 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e4dd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/source
2025-03-11 01:26:39,809 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e47a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/source
2025-03-11 01:26:39,810 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5520>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/source
2025-03-11 01:26:39,810 - ERROR - Error al unirse a la reunión: HTTPConnectionPool(host='localhost', port=37107): Max retries exceeded with url: /session/235bf002e4f46da2e8a6a88debb6a11a/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e6e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 01:26:39,811 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e7110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot
2025-03-11 01:26:39,812 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e7290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot
2025-03-11 01:26:39,812 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e7410>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot
2025-03-11 01:26:39,813 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=37107): Max retries exceeded with url: /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e75c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 01:26:39,813 - INFO - Permaneciendo en la reunión por 60 minutos
2025-03-11 01:26:39,813 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5c40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot
2025-03-11 01:26:39,814 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e4bf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot
2025-03-11 01:26:39,814 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot
2025-03-11 01:26:39,814 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=37107): Max retries exceeded with url: /session/235bf002e4f46da2e8a6a88debb6a11a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9eab0e5b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 01:26:39,814 - INFO - Todavía en la reunión - 0 minutos transcurridos
2025-03-11 01:26:41,843 - INFO - Cerrando el navegador
2025-03-11 01:26:46,041 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 01:26:46,354 - INFO - Driver headless inicializado correctamente
2025-03-11 01:26:46,354 - INFO - Intentando unirse a la reunión como invitado: https://meet.google.com/whq-cfhh-eji
2025-03-11 01:27:09,978 - INFO - URL actual: https://meet.google.com/whq-cfhh-eji
2025-03-11 01:27:10,081 - INFO - Captura guardada: screenshots/1_pagina_meet_cargada_20250311_012709.png
2025-03-11 01:27:10,081 - INFO - Ingresando nombre de invitado: Invitado Bot
2025-03-11 01:27:46,919 - INFO - Selector para nombre input[type='text'] falló: Message: 
Stacktrace:
#0 0x5561a47c9a1a <unknown>
#1 0x5561a4281390 <unknown>
#2 0x5561a42d2c85 <unknown>
#3 0x5561a42d2eb1 <unknown>
#4 0x5561a4321d64 <unknown>
#5 0x5561a42f8bfd <unknown>
#6 0x5561a431f07b <unknown>
#7 0x5561a42f89a3 <unknown>
#8 0x5561a42c460e <unknown>
#9 0x5561a42c5dd1 <unknown>
#10 0x5561a478fddb <unknown>
#11 0x5561a4793cbc <unknown>
#12 0x5561a4777392 <unknown>
#13 0x5561a4794834 <unknown>
#14 0x5561a475b1ef <unknown>
#15 0x5561a47b8038 <unknown>
#16 0x5561a47b8216 <unknown>
#17 0x5561a47c8896 <unknown>
#18 0x7f7f64416aa4 <unknown>
#19 0x7f7f644a3c3c <unknown>

2025-03-11 01:27:55,257 - INFO - Cerrando el navegador
2025-03-11 01:47:27,490 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 01:47:27,845 - INFO - Driver headless inicializado correctamente
2025-03-11 01:47:27,845 - INFO - Iniciando proceso de login en Google
2025-03-11 01:47:28,836 - INFO - Esperando campo de email...
2025-03-11 01:47:29,206 - INFO - Captura guardada: screenshots/1_email_ingresado_20250311_014729.png
2025-03-11 01:47:29,387 - INFO - Email ingresado, pasando a contraseña
2025-03-11 01:47:29,387 - INFO - Esperando campo de contraseña...
2025-03-11 01:47:33,190 - INFO - Captura guardada: screenshots/2_password_ingresado_20250311_014733.png
2025-03-11 01:47:43,332 - INFO - Intentando encontrar botón por texto
2025-03-11 01:47:43,592 - INFO - Login completado exitosamente
2025-03-11 01:47:43,714 - INFO - Captura guardada: screenshots/3_login_completado_20250311_014743.png
2025-03-11 01:47:43,721 - INFO - Detectada página post-login, continuando...
2025-03-11 01:47:50,185 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-11 01:48:05,485 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 01:48:05,649 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250311_014805.png
2025-03-11 01:48:05,778 - INFO - Captura guardada: screenshots/esperandocontroles_20250311_014805.png
2025-03-11 01:48:05,778 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-11 01:48:08,607 - INFO - Cerrando el navegador
2025-03-11 01:51:04,966 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 01:51:05,294 - INFO - Driver headless inicializado correctamente
2025-03-11 01:51:05,294 - INFO - Iniciando proceso de login en Google
2025-03-11 01:51:06,447 - INFO - Esperando campo de email...
2025-03-11 01:51:06,886 - INFO - Captura guardada: screenshots/1_email_ingresado_20250311_015106.png
2025-03-11 01:51:07,080 - INFO - Email ingresado, pasando a contraseña
2025-03-11 01:51:07,080 - INFO - Esperando campo de contraseña...
2025-03-11 01:51:10,855 - INFO - Captura guardada: screenshots/2_password_ingresado_20250311_015110.png
2025-03-11 01:51:21,006 - INFO - Intentando encontrar botón por texto
2025-03-11 01:51:21,260 - INFO - Login completado exitosamente
2025-03-11 01:51:21,367 - INFO - Captura guardada: screenshots/3_login_completado_20250311_015121.png
2025-03-11 01:51:21,377 - INFO - Detectada página post-login, continuando...
2025-03-11 01:51:28,053 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-11 01:51:42,984 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 01:51:43,071 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250311_015142.png
2025-03-11 01:51:43,185 - INFO - Captura guardada: screenshots/esperandocontroles_20250311_015143.png
2025-03-11 01:51:43,185 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-11 01:51:48,292 - INFO - Captura guardada: screenshots/controlesnada_20250311_015148.png
2025-03-11 01:51:48,441 - INFO - Cámara desactivada con selector: [data-is-muted='false'][aria-label*='cámara']
2025-03-11 01:51:48,653 - INFO - Micrófono desactivado con selector: [data-is-muted='false'][aria-label*='micrófono']
2025-03-11 01:51:48,806 - INFO - Captura guardada: screenshots/5_antes_de_unirse_20250311_015148.png
2025-03-11 01:51:48,896 - INFO - Intentando con selector: [jsname='CQylAd']
2025-03-11 01:52:22,725 - INFO - Intentando con selector: button[jsname='Qx7uuf']
2025-03-11 01:52:56,589 - INFO - Intentando con selector: button[jsname='A5xaw']
2025-03-11 01:53:30,444 - INFO - Intentando con selector: button[data-idom-class='nCP5yc AjY5Oe DuMIQc LQeN7 jEvJdc QJgqC']
2025-03-11 01:54:04,299 - INFO - Intentando con selector: button[jscontroller='soHxf']
2025-03-11 01:54:04,426 - INFO - Botón 'Unirse ahora' encontrado y clicado
2025-03-11 01:54:14,521 - INFO - Captura guardada: screenshots/6_reunion_unido_20250311_015414.png
2025-03-11 01:54:14,521 - INFO - ¡Unido a la reunión exitosamente!
2025-03-11 01:54:14,522 - INFO - Permaneciendo en la reunión por 60 minutos
2025-03-11 01:54:14,614 - INFO - Captura guardada: screenshots/verificacion_0min_20250311_015414.png
2025-03-11 01:54:14,614 - INFO - Todavía en la reunión - 0 minutos transcurridos
2025-03-11 01:54:23,258 - INFO - Cerrando el navegador
2025-03-11 01:56:41,202 - INFO - patching driver executable /home/carevalo/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 01:56:41,546 - INFO - Driver headless inicializado correctamente
2025-03-11 01:56:41,546 - INFO - Iniciando proceso de login en Google
2025-03-11 01:56:42,553 - INFO - Esperando campo de email...
2025-03-11 01:56:42,942 - INFO - Captura guardada: screenshots/1_email_ingresado_20250311_015642.png
2025-03-11 01:56:43,131 - INFO - Email ingresado, pasando a contraseña
2025-03-11 01:56:43,131 - INFO - Esperando campo de contraseña...
2025-03-11 01:56:46,909 - INFO - Captura guardada: screenshots/2_password_ingresado_20250311_015646.png
2025-03-11 01:57:00,632 - INFO - Intentando encontrar botón por texto
2025-03-11 01:57:00,911 - INFO - Login completado exitosamente
2025-03-11 01:57:01,019 - INFO - Captura guardada: screenshots/3_login_completado_20250311_015700.png
2025-03-11 01:57:01,027 - INFO - Detectada página post-login, continuando...
2025-03-11 01:57:07,418 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-11 01:57:18,860 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 01:57:18,963 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250311_015718.png
2025-03-11 01:57:19,054 - INFO - Captura guardada: screenshots/esperandocontroles_20250311_015718.png
2025-03-11 01:57:19,055 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-11 01:57:24,156 - INFO - Captura guardada: screenshots/controlesnada_20250311_015724.png
2025-03-11 01:57:24,310 - INFO - Cámara desactivada con selector: [data-is-muted='false'][aria-label*='cámara']
2025-03-11 01:57:24,456 - INFO - Micrófono desactivado con selector: [data-is-muted='false'][aria-label*='micrófono']
2025-03-11 01:57:24,584 - INFO - Captura guardada: screenshots/5_antes_de_unirse_20250311_015724.png
2025-03-11 01:57:24,791 - INFO - Captura guardada: screenshots/6_antes_de_unirse_20250311_015724.png
2025-03-11 01:57:24,791 - INFO - Intentando con selector: [aria-label*='Solicitar unirse']
2025-03-11 01:57:58,651 - INFO - Intentando con selector: [aria-label*='Join now']
2025-03-11 01:58:32,515 - INFO - Intentando con selector: button[data-mdc-dialog-action='join']
2025-03-11 01:59:06,361 - INFO - Intentando encontrar botón por texto
2025-03-11 01:59:06,545 - INFO - Encontrado botón con texto: Solicitar unirse
2025-03-11 01:59:20,308 - INFO - Captura guardada: screenshots/6_reunion_unido_20250311_015920.png
2025-03-11 01:59:20,308 - INFO - ¡Unido a la reunión exitosamente!
2025-03-11 01:59:20,308 - INFO - Permaneciendo en la reunión por 60 minutos
2025-03-11 01:59:20,401 - INFO - Captura guardada: screenshots/verificacion_0min_20250311_015920.png
2025-03-11 01:59:20,401 - INFO - Todavía en la reunión - 0 minutos transcurridos
2025-03-11 02:03:57,558 - INFO - Cerrando el navegador
2025-03-11 15:40:49,092 - ERROR - Google Chrome no está instalado. Instálalo con: sudo apt install google-chrome-stable
2025-03-11 15:42:41,047 - INFO - patching driver executable /root/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 15:42:41,753 - INFO - Driver headless inicializado correctamente
2025-03-11 15:42:41,761 - INFO - Iniciando proceso de login en Google
2025-03-11 15:42:42,297 - INFO - Esperando campo de email...
2025-03-11 15:42:44,487 - INFO - Captura guardada: screenshots/1_email_ingresado_20250311_154244.png
2025-03-11 15:42:44,631 - INFO - Email ingresado, pasando a contraseña
2025-03-11 15:42:44,631 - INFO - Esperando campo de contraseña...
2025-03-11 15:42:49,439 - INFO - Captura guardada: screenshots/2_password_ingresado_20250311_154249.png
2025-03-11 15:42:59,597 - INFO - Intentando encontrar botón por texto
2025-03-11 15:42:59,611 - INFO - Login completado exitosamente
2025-03-11 15:42:59,718 - INFO - Captura guardada: screenshots/3_login_completado_20250311_154259.png
2025-03-11 15:42:59,726 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-11 15:43:13,665 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 15:43:13,831 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250311_154313.png
2025-03-11 15:43:13,952 - INFO - Captura guardada: screenshots/esperandocontroles_20250311_154313.png
2025-03-11 15:43:13,952 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-11 15:43:19,122 - INFO - Captura guardada: screenshots/controlesnada_20250311_154318.png
2025-03-11 15:44:38,453 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a19a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,455 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef259429190>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,455 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a1700>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,459 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a1370>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,461 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a1df0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,461 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a2030>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,462 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a25a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,464 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a27e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,466 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a2a20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,477 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a2f90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,482 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a31d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,484 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a3410>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/element
2025-03-11 15:44:38,496 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a29c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot
2025-03-11 15:44:38,509 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a2cc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot
2025-03-11 15:44:38,511 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a29f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot
2025-03-11 15:44:38,514 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=37639): Max retries exceeded with url: /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a2660>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 15:44:38,516 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a1160>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/source
2025-03-11 15:44:38,521 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a1fd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/source
2025-03-11 15:44:38,523 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a22d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/source
2025-03-11 15:44:38,524 - ERROR - Error al unirse a la reunión: HTTPConnectionPool(host='localhost', port=37639): Max retries exceeded with url: /session/935f82b4ae7ee48a600c2dac32eefe0c/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a2000>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 15:44:38,533 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a1c40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot
2025-03-11 15:44:38,534 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a1af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot
2025-03-11 15:44:38,541 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a1070>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot
2025-03-11 15:44:38,542 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=37639): Max retries exceeded with url: /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a0f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 15:44:38,542 - INFO - Permaneciendo en la reunión por 60 minutos
2025-03-11 15:44:38,545 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a3500>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot
2025-03-11 15:44:38,546 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a3740>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot
2025-03-11 15:44:38,550 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a38c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot
2025-03-11 15:44:38,551 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=37639): Max retries exceeded with url: /session/935f82b4ae7ee48a600c2dac32eefe0c/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ef2593a3a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 15:44:38,552 - INFO - Todavía en la reunión - 0 minutos transcurridos
2025-03-11 15:44:44,881 - INFO - Cerrando el navegador
2025-03-11 15:52:32,363 - INFO - patching driver executable /root/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-11 15:52:32,941 - INFO - Driver headless inicializado correctamente
2025-03-11 15:52:32,944 - INFO - Iniciando proceso de login en Google
2025-03-11 15:52:34,815 - INFO - Esperando campo de email...
2025-03-11 15:52:35,418 - INFO - Captura guardada: screenshots/1_email_ingresado_20250311_155235.png
2025-03-11 15:52:35,598 - INFO - Email ingresado, pasando a contraseña
2025-03-11 15:52:35,599 - INFO - Esperando campo de contraseña...
2025-03-11 15:52:39,510 - INFO - Captura guardada: screenshots/2_password_ingresado_20250311_155239.png
2025-03-11 15:52:49,671 - INFO - Intentando encontrar botón por texto
2025-03-11 15:52:49,687 - INFO - Login completado exitosamente
2025-03-11 15:52:49,781 - INFO - Captura guardada: screenshots/3_login_completado_20250311_155249.png
2025-03-11 15:52:49,789 - INFO - Intentando unirse a la reunión: https://meet.google.com/cri-vaob-nyw
2025-03-11 15:53:03,690 - INFO - URL actual: https://meet.google.com/cri-vaob-nyw
2025-03-11 15:53:03,854 - INFO - Captura guardada: screenshots/4_pagina_meet_cargada_20250311_155303.png
2025-03-11 15:53:04,007 - INFO - Captura guardada: screenshots/esperandocontroles_20250311_155303.png
2025-03-11 15:53:04,008 - INFO - Esperando que aparezcan controles de audio/vídeo y botón de unirse...
2025-03-11 15:53:09,175 - INFO - Captura guardada: screenshots/controlesnada_20250311_155309.png
2025-03-11 15:53:36,427 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391490>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,431 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,432 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780390bf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,435 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391a30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,439 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391c70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,439 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391eb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,444 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780392420>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,445 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780392660>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,447 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e47803928a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,453 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780392e10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,457 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780393050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,458 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780393290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,462 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780392990>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,466 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780392930>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,469 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e47803924e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,472 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,474 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391f40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,478 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/element
2025-03-11 15:53:36,483 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780390ec0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/screenshot
2025-03-11 15:53:36,484 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780390b00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/screenshot
2025-03-11 15:53:36,485 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780393410>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/screenshot
2025-03-11 15:53:36,488 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=52801): Max retries exceeded with url: /session/e401541c54ba32dad9fd6c13fae9583b/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e47803935c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 15:53:36,489 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780393830>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/source
2025-03-11 15:53:36,490 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780393a40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/source
2025-03-11 15:53:36,492 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780393bf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/source
2025-03-11 15:53:36,497 - ERROR - Error al unirse a la reunión: HTTPConnectionPool(host='localhost', port=52801): Max retries exceeded with url: /session/e401541c54ba32dad9fd6c13fae9583b/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780393d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 15:53:36,498 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e47803935f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/screenshot
2025-03-11 15:53:36,499 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e47803934d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/screenshot
2025-03-11 15:53:36,501 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780390cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/screenshot
2025-03-11 15:53:36,503 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=52801): Max retries exceeded with url: /session/e401541c54ba32dad9fd6c13fae9583b/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 15:53:36,508 - INFO - Permaneciendo en la reunión por 60 minutos
2025-03-11 15:53:36,508 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391cd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/screenshot
2025-03-11 15:53:36,509 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780390e00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/screenshot
2025-03-11 15:53:36,511 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780391c40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e401541c54ba32dad9fd6c13fae9583b/screenshot
2025-03-11 15:53:36,515 - ERROR - Error al capturar pantalla: HTTPConnectionPool(host='localhost', port=52801): Max retries exceeded with url: /session/e401541c54ba32dad9fd6c13fae9583b/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e4780392000>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-11 15:53:36,516 - INFO - Todavía en la reunión - 0 minutos transcurridos
2025-03-11 15:53:38,043 - INFO - Cerrando el navegador
